version: '3.7'
services:
   web:
    build: . 
    command: gunicorn petadoption_project.wsgi -b 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
    environment: # env variables
        - ENVIRONMENT=production
        - POSTGRES_HOST=ec2-35-171-219-205.compute-1.amazonaws.com
        
        
   db:
     image: postgres:11
    