version: '3.7'
services:
   web:
    build: . 
    command: python /petadoption/manage.py runserver 0.0.0.0:8000
    
    volumes:
      - .:/petadoption
    ports:
      - 8000:8000
    depends_on:
      - db
    environment: # env variables
        - ENVIRONMENT = development
        - POSTGRES_NAME=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        
        
   db:
     image: postgres:11
     volumes:
       - postgres_data:/var/lib/postgresql/data/
     environment:
        - POSTGRES_PASSWORD=postgres  
 
volumes:
  postgres_data:        