# Generated by Django 2.2.7 on 2024-03-12 07:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('breed', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('age', models.DecimalField(decimal_places=0, max_digits=6)),
                ('color', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
