# Generated by Django 2.2.7 on 2024-03-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animalimage',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
