# Generated by Django 2.2.7 on 2024-03-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20240314_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
